### ISSUE TITLE
RS92 Ozone

### ISSUE THREAD

**Issue by OK1SLM** [projecthorus/radiosonde_auto_rx#139]
RS92 Why doesn't it read sensor data?

**Comment by darksidelemm** [comment]
What are you asking here? Why aren't we decoding Ozone data, or RS92 sensor data in general?

You do realise that Vaisala doesn't provide documentation on the telemetry, and all of this has to be reverse engineered, which is incredibly time consuming? I think our effort would be better spent on radiosonde types that are not obsolete (i.e. the RS41) rather than the RS92.
