### ISSUE TITLE
DFM mis-decode occur

### ISSUE THREAD

**Issue by AstroTaka** [projecthorus/radiosonde_auto_rx#709]
About testing branch, when decoding DFM-606212, suddenly DFM-C325D3 is decoded only once...

I cannot judge whether it is acceptable issue or not.
So I make this issue.

I uploaded several files.
https://drive.google.com/drive/folders/1CgDClOQMtcroTSVTHLp4PRBTWg8u1gIr?usp=share_link

Please check it.

**Comment by AstroTaka** [comment]
I received the next DFM sonde.
And DFM-605796 is decoded 7A0295, DE93B9 and 6057D6 also...

I uploaded several files.
https://drive.google.com/drive/folders/1KFR7mY57B7sNb6CflmhxasGCtBxuImyb?usp=share_link

Please check it.

**Comment by rs1729** [comment]
Thanks for the test data.
First I checked the raw file and the bin file, however using `dfm09mod` directly I didn't get wrong SNs, the frames you listed had the right SN. But there was one frame with implausible/incorrect altitude, probably that passed the ecc error correction count check, this can happen.
Then I looked at the `fsk_demod` output as in the log file. This showed the SN with hex characters you mention above. Don't know exactly why `fsk_demod` produces more frames like this, maybe it would require a lower error-count threshold or a higher SNR. One difference is that `fsk_demod` can get out of sync and the information about the distance between packets could be distorted.

Anyways, such a serial number should not end up in the JSON output. The decoder prints the SN only if it is the same as the previously decoded SN. However for JSON output the last SN is used, and this cannot be reset if the SN changes, because it would end up in a loop with SN=0. Thus I added a new SN for output that is only updated when it is equal to the previous, i.e. if the normal decoder output would print the SN.
Additionaly I could test if the DFM-06 SN6 nibbles are decimals (BCD), although it should be unlikely that the same decoding error happens two times in a row.
However now we could get frames that belong to a new DFM and new SN that outputs JSON with the old SN until it is updated.
Best would be to reset the output-SN until confirmed. Less JSON frames, but more reliable JSON data.

Reliable DFM decoding is a pain...
Will do some more testing and update the decoder later this night. I'm afraid it will still be a compromise.

**Comment by AstroTaka** [comment]
Thank you very much!!

I will try again after you release the next version.

**Comment by darksidelemm** [comment]
I've updated the testing branch with the new dfm09mod, and have bumped the version to -beta19 (really need to get this released soon!)

**Comment by AstroTaka** [comment]
I have already updated to beta 19.
I will post the result.

**Comment by AstroTaka** [comment]
I checked 5 times since this morning.
Before update, I can easy to see the problem.
After update, I cannot see the problem.

I keep watch this problem.

**Comment by AstroTaka** [comment]
I checked 6 times since at that morning.
I did not see the problem.

And suddenly DFM06 sonde stopped.
It is enough to check it.
So I close this issue.

**Comment by rs1729** [comment]
Thanks again for testing.

But what do you mean by

> And suddenly DFM06 sonde stopped.

Did the radiosonde stopped transmitting?
Or did the station stopped launching these radiosondes?
If radiosonde_rx stopped decoding, you wouldn't close the issue I guess.

Do you upload to Sondehub? Didn't see these old DFM-6/9 with additional sensors. Would be interesting to see what the DFM looks like, maybe somebody will recover one.

**Comment by AstroTaka** [comment]
@rs1729 I did not notice your comment.

DFM06 launch stopped.

I started to receive a sonde since Nov. 13. ( I am a beginner)

I received a sonde which launched at TATENO of Japan Meteorological Agency every day twice in a day.
I had no idea that I receive another sonde at another time and another place.

But I found two additional different launch place.
At each place, a sonde launched for every 3 hour.
The one place is iMS-100. Another place is DFM06P.
The both sonde stopped at 00:00 of Nov.18.

Since Nov. 23, a sonde started launch at almost same one and another one place.
The one place is iMS-100. Another place is DFM17.
At each place, a sonde launched for every several hour(3-6) at least.
Probably it will be over in near day.

Currently, I have no plan to upload to SondeHub because I am evaluating and I cannot guarantee to upload always.
And I modify a code sometimes.
I am afraid that my modified code cause a trouble to Sonde Hub.

`Didn't see these old DFM-6/9 with additional sensors. Would be interesting to see what the DFM looks like, maybe somebody will recover one.
`
I see. keep in my mind.

By the way, I found one problem about decoding DFM17.
DFM17 decoded as DFM09P sometimes.
I am collecting log which include IQ data.
If it is the Hamming code limitation, it is OK.
I hope you to check it.

**Comment by rs1729** [comment]
As mentioned in the other issue, in my opinion the DFM frame structure and error correction code without additional CRC/checksum is not ideal. Starting with the SN that should be the central ID for every frame etc.
The different DFM radiosondes have different number of repeating "channels", the last one contains the serial number.
The standard DFM-09 has the SN in channel 0xA. If there are additional sensors like pressure sensor, you have more "channels" as you have for DFM-09P with SN in 0xC. The new DFM-17 can have 0xC and 0xD, and also 0xB I believe.
So 0xC can be either DFM-09P or DFM-17, however the raw temperature data would be in different channels.
The DFM-17 has also other data like a counter, but always the problem, if you cannot rely on the decoded data, you could misinterpret the data. Perhaps you could track and collect the data to get confirmation, but then you would have less output or at least a delay.
If you take the data directly from rtl_sdr and look at the FM polarity, then the dfm09mod-decoder would see the DFM-06 with <-> polarity, the DFM-09(P) with <+> (except for the old DFM-09 with 8051 MCU that is like DFM-06), DFM-17 again <-> (also Pilotsonde I believe).
Different polarity could be because of a different transmitter or MCU, but I assume it is intentional, you could also view it as a different choice of Manchester type.
Here is the "guess table" from the decoder
```
                            V/Ti    Tf012           Rf
        0xA     DFM-09      5/6     0,3,4   'T+'    220k
        0xC     DFM-09P     7/8     1,5,6   'P+'    220k
        0xB     DFM-17      5/6     0,3,4   'T-'    332k
        0xC     DFM-17TU    5/6     0,3,4   'T-'    332k
        0xD     DFM-17P     7/8     1,5,6   'P-'    332k
```
If you know your receiver, it is easier to judge, but since this decoder is supposed to work also on e.g. a windows system running an old sdrsharp or maybe a soundcard that is inverting the audio, the decoder cannot depend on the polarity.
